queue_rules:
  - name: urgent
    conditions:
      - check-success=Node.js CI / build (12.x) (pull_request) 

  - name: default
    conditions:
      - check-success=Node.js CI / build (12.x) (pull_request) 

pull_request_rules:
  - name: move to urgent queue when 2 reviews and label urgent
    conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - label=urgent
    actions:
      queue:
        name: urgent

  - name: merge using the merge queue
    conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - check-success=Node.js CI / build (12.x) (pull_request) 
      - label!=urgent
    actions:
      queue:
        name: default
