queue_rules:
  - name: urgent
    conditions:
      - check-success=build (12.x)

  - name: default
    conditions:
      - check-success=build (12.x)

pull_request_rules:
  - name: move to urgent queue when 2 reviews and label urgent
    conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - label=urgent
    actions:
      queue:
        name: urgent

  - name: merge using the merge queue
    conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - check-success=build (12.x)
      - label!=urgent
    actions:
      queue:
        name: default
